language: node_js
node_js:
  - '11'

cache: npm
before_script:
  - npm ci

after_install:
  -npm run lint

after_success:
  -npm run test

deploy:
  -npm run deploy -- --branch=$TRAVIS_BRANCH --token=$zeitkey --name="awesome-nest-project-$TRAVIS_BRANCH"
