language: node_js
node_js:
  - "11"

cache: npm
before_script:
  - npm ci

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script: npm run test
    - stage: Build
      script: npm run build
    - stage: Deploy
      script: echo $TRAVIS_BRANCH
      script: npm run deploy
      

branches:
  only:
  - master