language: node_js
node_js:
  - '11'

before_script:
  - npm run lint

script:
  - npm run test

deploy:
  provider: heroku
  api_key: $herokukey
  app:
    master: awesome-nest-project-master
    develop: awesome-nest-project-develop
    test: awesome-nest-project-test
