language: node_js
node_js:
  - '11'

cache: npm
before_script:
  - npm ci

script:
  -npm run lint
  -npm run test
  -npm run deploy -- --branch=$TRAVIS_BRANCH --token=$zeitkey --name="awesome-nest-project-$TRAVIS_BRANCH"
